#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-pihole-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
             nethserver-pihole-set-hosts 5
             nethserver-pihole-docker-creation 10
             nethserver-pihole-set-reverse-proxy 20
));

templates2events("/var/lib/pihole/php-conf.d/99-memory.ini", $event);
templates2events("/etc/hosts", $event);

event_services($event,
               'dnsmasq' => 'restart'
);
